./submission/workloads/small/r0
./submission/workloads/small/r1
./submission/workloads/small/r2
./submission/workloads/small/r3
./submission/workloads/small/r4
./submission/workloads/small/r5
./submission/workloads/small/r6
./submission/workloads/small/r7
./submission/workloads/small/r8
./submission/workloads/small/r9
./submission/workloads/small/r10
./submission/workloads/small/r11
./submission/workloads/small/r12
./submission/workloads/small/r13


